In [1]:

import numpy as np

In [2]:
l=['samir',3,5.6]

In [3]:
type(l)

list

In [4]:
np.array(l)

array(['samir', '3', '5.6'], dtype='<U32')

In [5]:
type(np.array(l))

numpy.ndarray

In [6]:
a= np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
a[1][1]

np.int64(4)

In [8]:
b=np.array([1,2,5,6],ndmin=4)
b

array([[[[1, 2, 5, 6]]]])

In [9]:
b[0][0]

array([[1, 2, 5, 6]])

In [10]:
b[0][0][0][1]

np.int64(2)

In [11]:
np.asmatrix([1,2,3])


matrix([[1, 2, 3]])

In [13]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [16]:
np.zeros((3,4))
#np.empty((2,2))   #random number it can be 0. in 2x2 matrix

array([[1., 1.],
       [1., 1.]])

In [17]:
5+np.ones((2,2))

array([[6., 6.],
       [6., 6.]])

In [31]:
np.linspace(2,4,5) #create in between no from 2 to 4, number in 5 white-space and can be random.

array([2. , 2.5, 3. , 3.5, 4. ])

In [38]:
a=np.arange(4,40).reshape((6,6))
a

array([[ 4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [41]:
# a**2
pow(a,2)

array([[  16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400,  441],
       [ 484,  529,  576,  625,  676,  729],
       [ 784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521]])

In [44]:
b=np.arange(4,20).reshape((4,4))
b

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [49]:
c=np.arange(2,6)
c

array([2, 3, 4, 5])

In [51]:
b+c

array([[ 6,  8, 10, 12],
       [10, 12, 14, 16],
       [14, 16, 18, 20],
       [18, 20, 22, 24]])

In [57]:
c1=c.reshape(-1,1)  #arangeing it in colum formate
c1

array([[2],
       [3],
       [4],
       [5]])

In [58]:
b+c1

array([[ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [59]:
c1.T    #transfor or rotate row to col

array([[2, 3, 4, 5]])

In [61]:
b+c1.T

array([[ 6,  8, 10, 12],
       [10, 12, 14, 16],
       [14, 16, 18, 20],
       [18, 20, 22, 24]])

In [62]:
x=np.array([1,2,3])
y=x    #Shallow copy : y is referring to same address as x
y

array([1, 2, 3])

In [63]:
z=np.copy(x)   #Deep copy : Z is copying value from x but seat on different address
z

array([1, 2, 3])

In [67]:
x[0]=100
x
# id(x)

4384477936

In [68]:
y
# id(y)

4384477936

In [69]:
z
# id(z)

4384478800

In [71]:
id(x[0])

4384673456

In [72]:
id(y[0])

4384673328

In [73]:
id(x[0])==id(y[0])  #both returning value=100 even if address is different

True