In [2]:

import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [3]:
l=['samir',3,5.6]

In [4]:
type(l)

list

In [5]:
np.array(l)

array(['samir', '3', '5.6'], dtype='<U32')

In [8]:
type(np.array(l))

numpy.ndarray

In [9]:
a= np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [10]:
a[1][1]

np.int64(4)

In [13]:
b=np.array([1,2,5,6],ndmin=4)
b

array([[[[1, 2, 5, 6]]]])

In [16]:
b[0][0]

array([[1, 2, 5, 6]])

In [17]:
b[0][0][0][1]

np.int64(2)

In [23]:
np.asmatrix([1,2,3])


matrix([[1, 2, 3]])

In [25]:
np.formfunction(lambda i,j: i==j, (3,3))

AttributeError: module 'numpy' has no attribute 'formfunction'